# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modifytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifyer', models.CharField(max_length=100)),
                ('modifytime', models.CharField(default='', max_length=200)),
                ('modifyservertime', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'modifytime',
            },
        ),
        migrations.CreateModel(
            name='rebootserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebooter', models.CharField(max_length=100)),
                ('reboottime', models.CharField(default='', max_length=200)),
                ('rebootresult', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'reboot',
            },
        ),
        migrations.CreateModel(
            name='serverconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('detail', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'serverconfig',
            },
        ),
        migrations.CreateModel(
            name='taskinbackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('taskor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
